### ISSUE TITLE
redirect users on plugins page

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#12]
On activate we redirect the users Media -> Intergeo. If there are no maps available, we will show them either some useful links on how to use it or something related to this.

**Comment by selu91** [comment]
@contactashish13 let's add a green notification after the plugin install, which users can dismiss. The message will be lately edited.

**Comment by contactashish13** [comment]
so do you want to redirect or do you want to add a dismissable nag? If the latter, do you want it on the plugin listing screen like Akismet shows?

**Comment by selu91** [comment]
yes, a dismissable nag, on the plugin listing screen

**Comment by contactashish13** [comment]
will the message inside be an image or just text? in either case, will you style this since you said you want a green notification?

**Comment by ineagu** [comment]
@contactashish13  it will be just text, I think we can just use a standard wp notification style and maybe customize later on if we want.

**Comment by selu91** [comment]
@contactashish13 please add a security check here using nonce.

https://github.com/Codeinwp/intergeo-maps/commit/8114a1d6a9e3d346f5313205c54f9cdaf53494bf#diff-2ae54250c523c9ed56a97c45245d8857R6
