### ISSUE TITLE
translation ready plugin

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#13]
We would need to make the plugin translation ready:

https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

**Comment by contactashish13** [comment]
pushed changes to repo @selu91

**Comment by selu91** [comment]
please also add these:

* Text Domain: my-plugin
 * Domain Path: /languages

**Comment by contactashish13** [comment]
done

**Comment by selu91** [comment]
solved in https://github.com/Codeinwp/intergeo-maps/commit/80432b812dd52110b92b0c70c5fbe76d74021f9e
https://github.com/Codeinwp/intergeo-maps/commit/ccc96773ab79bdc5335a06594aefa4715706a0c6
