### ISSUE TITLE
intergeo simplify admin

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#19]
Hello Ash,

I would like to simplify the admin interface for intergeo. Here are the modifications i would like to do: 
1. Move the Overlays sections to be first and open by default. All other should be closed.
2. The subsection markers should be opened by default.
3. The enable drawing tools should be removed and the plugin should show them always. 
4. In the markers sections, we need to add a button, http://prntscr.com/bbgizp ( red square ), called add new marker.  When click will open a popup, similar with the one you see when clicking on edit : http://prntscr.com/bbgjjv . The html window will need to be a WYSIWYG editor, the wordpress one.

**Comment by selu91** [comment]
@contactashish13, in the marker popup i would like to offer the possibility to users to enter the location, either by address or longitude and latitude, smth similar with : 

http://prntscr.com/bd0kn9 from here: https://mapbuildr.com/ ( if you click on start building and add new location after ) 

Also, instead of icon url, please add a dropdown, similar with http://prntscr.com/bd0uo0 from the same address.

Let me know if you have any questions.

**Comment by selu91** [comment]
@contactashish13 regarding the dropdown, in the exemple provided, if you select custom, a new input will open to enter the URL. 

Regarding the icons, you can add the default, custom, a new marker which will take the image from the plugin assets. The 3rd option will be just a sample, we will add more after.

Thank you !

**Comment by contactashish13** [comment]
@selu91 I've pushed the change that allows users to enter location either by address or longitude and latitude. Please let me know if its alright.

**Comment by selu91** [comment]
@contactashish13 when adding a marker using a custom location is not added in the correct place. Also, on adding new, the previous place stays there. 

On edit, there is not place in the address location.

Please see video for example: 

https://drive.google.com/file/d/0B8cbkQkB9YbnQzZGcG01RmdUY28/view

**Comment by contactashish13** [comment]
@selu91 ok, so you want the marker to move to the location whether it be a selected location or lat/long?

And when editing, do you want the name shown as well i.e. place selected or lat/long? I assumed that was not required.

**Comment by selu91** [comment]
@contactashish13 yes, after the user save the marker, to move to the desired location, either is address or lat/long
On edit, can we check if there was a location, to show the name, and if lat/long to show to numbers ?

**Comment by contactashish13** [comment]
@selu91 done

**Comment by selu91** [comment]
@contactashish13 i see that the dropdown for icons is not ready yet, i think you forgot to add it.

Also, the overlay accordation is not closing on click, it always stays open. it should stay only for the first time.

Also, when a marker is added can we center the map automatically around it? When the second is added to center having both of them in the preview and so on?

Do you know where the marker title is used? I'm thought that is in the marker tooltip but it seems is not ?

**Comment by contactashish13** [comment]
@selu91 marker drop downs will take time. Maybe by day after tomorrow.  Will fix the overlay accordion in that as well.

Will see what I can do about centering.

Marker title is used in tooltip hover.

**Comment by selu91** [comment]
@contactashish13 i hover the tooltip and i see nothing, can you tell an use case?

**Comment by contactashish13** [comment]
@selu91 add a title, update the marker and the hover the mouse on the marker - the tooltip shows.

**Comment by contactashish13** [comment]
@selu91 added drop down for markers and fixed the issue with the overlays accordion. have not implemented centering yet.

**Comment by contactashish13** [comment]
@selu91 the map's bounds will be increased according to the marker that is being updated/added.

**Comment by selu91** [comment]
Hey @contactashish13,

there are some things left: 
 * When creating the first marker, the zoom is to aggresive, can you increase the range a bit more, the zoom is to small
 * I have added titles for two markers, when i click on them after, i see no tooltip, neither if i use it in frontend, in the maps listing page or builder.
* Can we save the current zoom and position when creating the map. Now if you check the video, after i saved the markers and centered them in the current view, after i save the map, in the listing page i dont see them, the view is different. 

https://drive.google.com/file/d/0B8cbkQkB9YbnMW1Zd3M3V3FnOTQ/view

**Comment by contactashish13** [comment]
@selu91 for "When creating the first marker, the zoom is to aggresive, can you increase the range a bit more, the zoom is to small", do you want me to zoom in more?

Can you send me an example where you cannot see the tooltip? Not a video, but maybe in the sandbox account?

**Comment by selu91** [comment]
@contactashish13, for the first question, no, zoom out more.

for the 2nd: 

http://ash-test.qsandbox.com/ 

access code: 0000
password: asd!@#
user: ash

You have a map created there, with one marker. When i click on it, no tooltip is shown.

Thanks !

**Comment by contactashish13** [comment]
@selu91 Strange, but I can see the tooltip. Have attached a snapshot.

![img_20160616_201352](https://cloud.githubusercontent.com/assets/12953439/16141498/f1321ffe-3479-11e6-876d-92f911dd255c.jpg)

Rest all features have been added.

**Comment by selu91** [comment]
Ah, i thought that is  tooltip which is prompted on click. It's ok now.

Thanks !
