### ISSUE TITLE
investigate conflict with uber menu

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#20]
@contactashish13 can you investigate if there is an issue with ubermenu, v3.2.4. 

https://wordpress.org/support/topic/maps-freezing-after-a-few-seconds#post-8471693

**Comment by contactashish13** [comment]
@selu91 seems to be a paid plugin. do you have a copy?

**Comment by selu91** [comment]
@ineagu do you have one ?

**Comment by ineagu** [comment]
nop, maybe we can ask them for a copy ( ubermenu )

**Comment by selul** [comment]
@mariusghitulescu can you help me to get a copy from them ? We can ask if they provide us for testing the conflict ?

**Comment by mariusghitulescu** [comment]
Got it, here's the feedback from them: 

> Most commonly, maps conflicts stem from loading two copies of the Google Maps API, as I'm sure you know - so for your reference, you can disable UberMenu's copy in the settings - http://sevenspark.com/docs/ubermenu-3/faqs/google-maps
> 
> By the way, I checked out the URL from that forum post you linked to, and I didn't encounter any JS errors, for whatever that is worth.  The two plugins appear to be working together without issue.

**Comment by selul** [comment]
@contactashish13 can you check if you can do a fix without needing any extra settings from the ubermenu side  ?

**Comment by contactashish13** [comment]
@selul i couldn't replicate the issue of the drag freezing even if the maps api was being loaded by ubermenu. but I could see the error in the console that maps api has been loaded multiple times. i've dequeued their google maps if it is loaded and loaded ours. it works properly without throwing that error.
