### ISSUE TITLE
Give plugin a dedicated settings page

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#23]
Right now the plugin settings is in a weird place -> a sub setting of "Media" the settings for the plugin is also under Settings->Media

Not sure why we have it working like that @selul

**Comment by selul** [comment]
@UVLabs i dont understand your question :D ?

**Comment by UVLabs** [comment]
@selul I installed the plugin for the second time I believe and it's hard finding where to go for settings off the bat, example this other map plugin has a top level settings page: http://prntscr.com/bpyvl1

But ours is a sub setting menu of media, I don't think maps are classified as Media: http://prntscr.com/bpyvxb

You also have to go to settings->Media if you want to do some more configuration, this is strange UX: http://prntscr.com/bpywhs

So maybe we should have the plugin create a top level settings page called "Intergeo Maps" or something

**Comment by selul** [comment]
@UVLabs yes, i think would be a good idea. 

@ineagu should we address this on the next update? I think the top level menu is the best choice, Maybe no Intergeo Maps, just Maps or Wordpress Maps ? Also the general settings could be a submenu of the top level page

**Comment by ineagu** [comment]
I would add a sub-page under settings called intergeo maps, which can residirect to current setting page, what do you think?

A top level setting page isn't super nice for the users if you aren't using the plugin often, since it takes space in sidebar

**Comment by selul** [comment]
@UVLabs  @ineagu 

What do you think to integrate the settings in the current page ( from Media ), as separate tab, in order  to not have them spread all over the place ?

Also to rename the submenu from Intergeo Maps To Wordpress Maps or Maps ?

**Comment by ineagu** [comment]
I don't understand, do we have another setting page ?

On Tue, Jul 12, 2016 at 11:27 AM, Marius Cristea <notifications@github.com>
wrote:

> @UVLabs <https://github.com/UVLabs> @ineagu <https://github.com/ineagu>
>
> What do you think to integrate the settings in the current page ( from
> Media ), as separate tab, in order to not have them spread all over the
> place ?
>
> Also to rename the submenu from Intergeo Maps To Wordpress Maps or Maps ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/intergeo-maps/issues/23#issuecomment-231986135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DD3PKi5oABdqxfL7sUcC8x3iMTw1ks5qU134gaJpZM4JHI1r>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selul** [comment]
Yes, there are plugin relates settings unde Esettings -> Media  @ineagu

**Comment by UVLabs** [comment]
@selul @ineagu Media in WP to most people would deal with files, pictures, videos etc, usually plugins that have a submenu under media are plugins that do some kind of media management, Our maps plugin doesn't really fall into anything related to media so we should move it somewhere else, maybe under settings as Ionut said.

**Comment by UVLabs** [comment]
And yes we could do the tab setting you mentioned. We also have this same issue with Visualizer plugin

**Comment by ineagu** [comment]
for me this is tricky, in order to add charts for example in the post
editor easily you need to go to "Add Media" . Having a top level menu like
we have for ReviveOldPost for example, isn't the best practice, too much
clutter for the user, so I would rather do small things that will help us
avoiding the confusion.

1. Add a link to settings here : http://prntscr.com/bsa0mv
2. Add a settings link in settigs->intergeo maps ( that will redirect to
the main one under media ).

I think this should be enough.

On Wed, Jul 13, 2016 at 5:23 AM, Uriahs Victor <notifications@github.com>
wrote:

> And yes we could do the tab setting you mentioned. We also have this same
> issue with Visualizer plugin
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/intergeo-maps/issues/23#issuecomment-232245673>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DK5wHBnhjvuWrQcjmh72ka_Hxt3bks5qVFoggaJpZM4JHI1r>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selul** [comment]
Why is this necesarly 

> 2. Add a settings link in settigs->intergeo maps ( that will redirect to
> the main one under media ).


if it's just a redirect  ?

**Comment by ineagu** [comment]
is not necesary, it just might help users find it easier, some people are
using directly there for a setting page

On Wed, Jul 13, 2016 at 9:34 AM, Marius Cristea <notifications@github.com>
wrote:

> Why is this necesarly
>
>
>    1. Add a settings link in settigs->intergeo maps ( that will redirect
>    to the main one under media ).
>
> if it's just a redirect ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/intergeo-maps/issues/23#issuecomment-232278790>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DK80L_t4brQiQI6Ocvfu-_pCxjZKks5qVJUTgaJpZM4JHI1r>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selul** [comment]
ok, got it, i will prepare the specs next week.

**Comment by selul** [comment]
#28 added
