### ISSUE TITLE
Adding around 30 markers issue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#26]
If you add around 30 markers and save the shortcode then use it on the site then you will notice that not all show up.

This is a view while adding the markers: http://prntscr.com/bsmz6h

This is a view when actually rendered, in this case 2 markers at the bottom disappeared:  http://prntscr.com/bsncyl 

@selul

**Comment by selul** [comment]
@contactashish13 can you please investigate

**Comment by contactashish13** [comment]
@UVLabs i cannot replicate this error. I tried to add 30 markers using the draw feature as well as using the add marker button but all of them show up. Maybe there is a specific use case?

**Comment by UVLabs** [comment]
@contactashish13 did you try adding the shortcode to a page and checking if all the markers rendered? I just saw another ticket come in where a user said at 18 markers there seems to be a limit where it replaces the previous one.

**Comment by contactashish13** [comment]
Yes I did and there was no problem.

Regards, 
Ash

**Comment by selul** [comment]
@UVLabs do you have any environment where we can check  ?

**Comment by UVLabs** [comment]
@selul I believe I was testing on localhost at the time, I will check on an online live environment and let you know, thanks

**Comment by selul** [comment]
@UVLabs i can provide you a qsandbox environment if you want

**Comment by UVLabs** [comment]
I tried 43 markers on ash-test.qsandbox.com and they seem to show up even after they are saved.
