### ISSUE TITLE
settings page

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#28]
@contactashish13 i would like build a setting page for intergeo, with this settings: 

http://prntscr.com/budy7p 

We currently have them in Settings->Media, i would like to remove them from there and build a separate page. 

The page can be accessed in two ways: 
1. Add a link in the Settings area, Settings ->  Intergeo Maps which will show this page. 
2. In Media-> Intergeo Maps add the button "Maps Settings" which will redirect to the settings page, here : http://prntscr.com/budzn8 same style as the add new btn. 

Let me know if you have any questions

**Comment by contactashish13** [comment]
@selul maybe we should also add a nag notice on the maps listing page so that the user adds an api key and warn the user that maps might not display if the key is not added. It appears google is making this mandatory

**Comment by selul** [comment]
yes, let's do this.

**Comment by selul** [comment]
i have added some comments here : 

https://github.com/Codeinwp/intergeo-maps/commit/1d75613391b55e4fb2e514d1c6c4621c7115a8ca
