### ISSUE TITLE
feedback integration

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#29]
@contactashish13 i will like to integrate a feedback mechanism in the intergeo plugin. 

After some triggers are met i would like to show a nag notification in the plugin area, both settings and maps listing page. 

The nag notification will have a description to engage the users to leave a review and 3 buttons: 
- remove the notification btn, will hide the notification 
-  ok btn, which will redirect the users to the review page
- 'i've done it', which will have the same behaviour as the remove  btn 

For the notification to show up we would need to have some triggers. 

For each trigger, we would have separate description and text for btns and links.

For one trigger we can have multiple sets of descriptions and btns settings. 

One set for the notification  will have the following components: 
- descrption ( mandatory, dont show the notification if this is empty ) 
- link for ok btn  ( mandatory, dont show the notification if this is empty ) 
- text for ok btn ( mandatory, dont show the notification if thihs is empty ) 
- text for hide btn ( optional, default value is 'Hide' ) 
- text for i've done it btn ( optional, default value is "I've already done it" ) 

The triggers for the intergeo will be : 
- after user created 3 maps
- after user has the plugin installed for more the 1 week
- after user has used one map in the frontend ( you can view this by editing the maps rendering code, see if is rendered from wp-admin or not, and save an option when is this first done  ) . 

All of triggers will have an OR check, meaning just one of them is enough to show the notification, one time only. 

After the notification will show and user will press either of 3 btns, the user will never receive any other notification.

After one trigger is met, we need to postpone the notification to show, after 6 hours and not show right away. We need to be consistent and use the apropiate set of notifications for the trigger used. In case we have multiple sets of notifications for one trigger, we will do a random selection between them.

Please try to make to make the scription modular as possible in order to include it in other plugins too lately.

**Comment by contactashish13** [comment]
@selul should this be like a notice or like a thickbox popup?

**Comment by selul** [comment]
@contactashish13 will be a nag notification, like the you used to redirect the users from the plugins page to the intergeo maps listing page.

**Comment by contactashish13** [comment]
@selul pushed in the changes

**Comment by selul** [comment]
@contactashish13 

1. please use an action hook here, intergeo_shortcode_render_before and pass there also the atts parameter. Please hook to that action the function that marks the view. https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#diff-828e0013b8f3bc1bb22b4f57172b019dR736

2. https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#diff-828e0013b8f3bc1bb22b4f57172b019dR1031 here also affects when user will update the plugin ? I would like to also take this into consideration and not only when is user installing the plugin for the first time. 

3. Please use 4 for post_per_page here https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#diff-828e0013b8f3bc1bb22b4f57172b019dR1206 we just need to see if is greater than 3 not count all the maps. 

4. Please sanitize the slug before updating. https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#diff-828e0013b8f3bc1bb22b4f57172b019dR1191

5. https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#diff-828e0013b8f3bc1bb22b4f57172b019dR1154 can we use a filter for getting the html of the notification ? We can hook to that filter a function which build the html of the notification in here https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#diff-828e0013b8f3bc1bb22b4f57172b019dR1134 What do you think ?

**Comment by selul** [comment]
@contactashish13 i have added you a comment here: 

https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#commitcomment-18325674

**Comment by selul** [comment]
@contactashish13 also here: https://github.com/Codeinwp/intergeo-maps/commit/ec2c09ec2e466875f13a6ecef5f7e368097862a0#diff-828e0013b8f3bc1bb22b4f57172b019dR1031 you have not confirmed if on update, we save the timestamp ? 

We have 2 types of events when the timestamp need to be saved: 

- plugin activation, from Wordpress -> Plugins -> Activate btn 

- plugin update , when the user will update the plugin to the version containing the feedback script. let's say the version containing the feedback script is 2.0.0 . When the user will update, i would like to save the timestamp, but when he will update further on 2.2.0 for instance, to no longer update the timestamp.

**Comment by contactashish13** [comment]
@selul my recent most commit had the changes. I'm updating the timestamp every time the user activates the plugin. 

for plugin update, do you want me to check for a particular version?

**Comment by selul** [comment]
@contactashish13 no, no particular version, i would like just to preserve the timestamp across plugin updates.

**Comment by contactashish13** [comment]
@selul I'm confused. initially I was preserving the timestamp across updates and then on the basis of your   comment I updated the timestamp at every activation. can you tell me what behavior you prefer?

**Comment by selul** [comment]
@contactashish13, my only concern is to  preserve the timestamp across
updates
Pe 22 iul. 2016 08:40, "contactashish13" <notifications@github.com> a scris:
