### ISSUE TITLE
Cloud and Weather Layers are not working

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/intergeo-maps#3]
When creating a map, enabling Cloud and Weather layers do not work.

Update: http://dirk.net/2015/06/12/google-maps-weather-layer-not-working/

Those layers do not exist anymore, we should remove them completely.

@ineagu @selu91 @rodica-andronache

**Comment by selu91** [comment]
they are no longer available due to google maps api. fixed in https://github.com/Codeinwp/intergeo-maps/commit/4a1338301d888b540e7ff3400d740c6defd6c8fc
