### ISSUE TITLE
Google Map Wrong Instructions Api updated

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#30]
The instructions for creating an app are wrong, also just like mentioned in Visualizer, user has to go to Settings->Media to enter their API key rather than everything being centralized.

I was able to find instructions from another maps plugin: http://www.wpgmaps.com/documentation/creating-a-google-maps-api-key/

@selul

**Comment by selul** [comment]
@UVLabs can you please edit them and send a pull request ? 

Thanks !

**Comment by UVLabs** [comment]
Will do @selul waiting for at least basilis or hardeep to come back on support

**Comment by selul** [comment]
@UVLabs do you have time to do it these days ?

**Comment by UVLabs** [comment]
@selul waiting for madalin to upload the video to youtube, I did a video tutorial

**Comment by selul** [comment]
@mileamadalin when this can be done ? A release is scheduled for wednesday

**Comment by selul** [comment]
@UVLabs meanwhile take a random video and when is ready we just replace the link. Please arrange the texts and page there to all be in place

**Comment by UVLabs** [comment]
@selul submitted pull request

**Comment by mileamadalin** [comment]
@selul everything is okay here? Something that I need to do?
