### ISSUE TITLE
Duplicate map issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/intergeo-maps#31]
@contactashish13 @selul we have an issue with duplicating a map. I created a duplicate map (which has Romania and London) and every time I make a new marker, one old one gets erased.

**Comment by selul** [comment]
@contactashish13 can you please check ?

**Comment by contactashish13** [comment]
@mileamadalin can you show me an example/video?

**Comment by selul** [comment]
@contactashish13 have you tried to replicate ?

**Comment by contactashish13** [comment]
@selul yes and I found no issue that is why I was asking for a video

**Comment by selul** [comment]
@mileamadalin can you guide @contactashish13 about the issue ?

**Comment by contactashish13** [comment]
@mileamadalin strangely I cannot replicate the issue. I created 25 markers and I got 25 markers when I revisited the map. I see 25 markers on the front end and also in the library.


![image](https://cloud.githubusercontent.com/assets/12953439/17409465/0aefebe0-5a8d-11e6-9038-a4d1b33c6371.png)

**Comment by selul** [comment]
@mileamadalin can you please do a step by step replication as it seems is not an isolated case ?

**Comment by selul** [comment]
closing as duplicate for #33
