### ISSUE TITLE
Old map markers disappear if created more than 20-22 markers

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/intergeo-maps#33]
As reported by several users, if you add a lot of markers to the map (like 20-25) then every time you save the map, a couple of them will be deleted. That should explain the issue.

**Comment by HardeepAsrani** [comment]
Previously reported here as well: https://github.com/Codeinwp/intergeo-maps/issues/26

**Comment by contactashish13** [comment]
@HardeepAsrani i've already tried to replicate it with no success.

**Comment by HardeepAsrani** [comment]
@selul Can you try to reproduce?

Both @UVLabs & I have tried and it worked, while it works properly for Ashish. We need a 4th opinion. :D

**Comment by selul** [comment]
@HardeepAsrani @UVLabs @mileamadalin can you try to reproduce it on qsandbox environment

**Comment by UVLabs** [comment]
Ok @selul @HardeepAsrani maybe @Basilakis can you help us replicate this? madalin is pretty busy for now it seems :)

**Comment by lemonmojo** [comment]
Having the same issue. I'm using Plugin Version 1.0.6 and Pro Add-On Version 1.2.0.

**Comment by selul** [comment]
@UVLabs @Basilakis @HardeepAsrani can you set up an online development environment where we can replicate this. try qsandbox.

**Comment by UVLabs** [comment]
This didn't happen on the qsandbox installation @selul http://ash-test.qsandbox.com/intergeo-map/

@lemonmojo could you please give us a list of plugins you are using on the website where you have this issue, Could you please test again?

**Comment by lemonmojo** [comment]
@UVLabs I just updated the plugin to 1.1.10 and now I'm having the same issue that I already had a month or two ago.
When I want to edit one of my maps I'm greeted by the following message:

> Please help us improve Intergeo Lite- Google Maps Plugin! If you opt-in, some data about your usage of Intergeo Lite- Google Maps Plugin will be sent to freemius.com. If you skip this, that's okay! Intergeo Lite- Google Maps Plugin will still work just fine.

It doesn't matter if I choose "Skip" or "Allow & Continue" I'm always being taken back to the same page. One of your developers fixed this by removing the specific code from my installation the last time around.

So I'm sorry but I can't test any improvement on this issue because I don't even get to see my maps now.

**Comment by lemonmojo** [comment]
Since you closed this issue, is it fixed?

**Comment by selul** [comment]
@lemonmojo we already have an open issue on this. Until we find a pattern to replicate the issue we can not move any further

**Comment by lemonmojo** [comment]
That's really unfortunate since I'm not able to use your product for more than 3 months now!

**Comment by Basilakis** [comment]
Hey Felix,

Could you please give us a step by step way to replicate the issue?
What steps we can follow or provide us an account, where we can login and see the issue happening.

Thanks a lot

**Comment by lemonmojo** [comment]
I'd love to! Unfortunately, like previously I can't even edit my maps now because of another issue. Please see the following short video: http://www.lemonmojo.com/temp/intergeomapsbug.mp4
