### ISSUE TITLE
PHP log error

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#37]
"Only variables should be passed by reference in /home/askwino7/public_html/winelab.net/wp-content/plugins/intergeo-maps/index.php on line 169"
 @selul 

Ticket: https://secure.helpscout.net/conversation/243661808/110143/?folderId=948378

**Comment by selul** [comment]
@contactashish13 can you check, it is related by the end function you use there, you should pass a variable not the function result

**Comment by contactashish13** [comment]
@selul I've pushed the changes in but I cannot create a new PR, maybe because the previous PR already exists.

**Comment by selul** [comment]
@contactashish13 yes, seems ok now
