### ISSUE TITLE
Fatal appear in the latest version 

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#39]
The following appear is appearing when trying to use the latest Visualizer for a lot of people:

Fatal error: Can't use function return value in write context in /home/content/n3pnexwpnas02_data02/66/3243266/html/wp-content/plugins/intergeo-maps/templates/library/list.php on line 3

I'm not able to reproduce this but a lot of people have reported it so far, like this: https://secure.helpscout.net/conversation/247226117/0/

**Comment by selul** [comment]
@contactashish13 can you have a look

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/intergeo-maps/pull/40

**Comment by HardeepAsrani** [comment]
Yup, opened it in the wrong plugin by mistake. -_-

**Comment by UVLabs** [comment]
@selul we need to release this patch :)

**Comment by UVLabs** [comment]
@selul @contactashish13 The latest commit fixes the maps showing but It shows the No API key notice when the api key is entered, and doesn't show it when there's no key. The conditional is backwards

**Comment by selul** [comment]
@contactashish13 can you investigate ?

**Comment by contactashish13** [comment]
@selul my bad. Have fixed it.
