### ISSUE TITLE
Market text disappears if added using text view

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/intergeo-maps#41]
If you add some Text/HTML in the text view (https://nimbus.everhelper.me/client/notes/share/574963/98d2efelbxzl86nrstpp) then it disappears once you save the map. @selul

**Comment by selul** [comment]
@contactashish13 can you check ?

**Comment by contactashish13** [comment]
@selul have removed the visual/text tabs so that this no longer causes confusion. PR: https://github.com/Codeinwp/intergeo-maps/pull/42
