### ISSUE TITLE
Impossible to view or edit my maps because data usage opt-in dialog won't go away

### ISSUE THREAD

**Issue by lemonmojo** [Codeinwp/intergeo-maps#44]
I can't view or update my maps because a dialog to opt-in to collecting data usage won't go away.
The following short video should explain the issue: [http://www.lemonmojo.com/temp/intergeomapsbug.mp4](http://www.lemonmojo.com/temp/intergeomapsbug.mp4)

**Comment by contactashish13** [comment]
@rodica-andronache the video file no longer exists.
