### ISSUE TITLE
Browser warning - parts of page are insecure

### ISSUE THREAD

**Issue by roger-richards** [Codeinwp/intergeo-maps#49]
Reported this issue to themeisle 2 months ago but the warning remains in the latest version. My WP site is full https.  Browser reports: "Part of this page are not secure (such as images.)"

Looking at the FireFox debug console:
Loading mixed (insecure) display content “http://maps.google.com/mapfiles/ms/icons/red-dot.png” on a secure page
https://maps.googleapis.com/maps-api-v3/api/js/27/2/util.js
Line 7

Can this be fixed?  As my WP site is for ecommerce, the browser warning is a worrisome to my potential customers.

**Comment by UVLabs** [comment]
@selul @contactashish13 didn't we patch this some time ago? we should change the URL to 

//maps.google.com/mapfiles/ms/icons/red-dot.png

**Comment by roger-richards** [comment]
Still not fixed in latest release. In FireFox debugger:

Loading mixed (insecure) display content “http://maps.google.com/mapfiles/ms/icons/red-dot.png” on a secure page

Can this be fixed or patched?

**Comment by roger-richards** [comment]
I should add, that since I use your paid plugin on a woocommerce site, having pages (with maps) that flag as insecure is a bad impression for customers (even though I know it is just this one tiny image!)

**Comment by UVLabs** [comment]
+1

**Comment by contactashish13** [comment]
@UVLabs can you confirm this issue exists? If so, please share a screenshot. I am not able to reproduce this.

**Comment by rodica-andronache** [comment]
@UVLabs

**Comment by roger-richards** [comment]
Not sure if this was ever fixed but now Wordpress is displaying an admin banner: "Your store does not appear to be using a secure connection."  Chrome inspect shows:
Mixed Content: The page at 'https://winelab.net/' was loaded over HTTPS, but requested an insecure image 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'. This content should also be served over HTTPS.
2util.js:125 Mixed Content: The page at 'https://winelab.net/' was loaded over HTTPS, but requested an insecure image 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'. This content should also be served over HTTPS.

I guess I could install another plugin to force HTTPS everywhere but why can't this be fixed?!

**Comment by contactashish13** [comment]
@mileamadalin can you please test and confirm that this issue exists.?

**Comment by mileamadalin** [comment]
@contactashish13 I tried to replicate this issue on a live webiste and I could not reproduce it. Works for me and I do not have the same issue as the customer.  Please see the images attached: 

![screenshot 2018-11-13 at 5 51 03 pm](https://user-images.githubusercontent.com/6906834/48425231-0cfa9380-e76d-11e8-9d2b-96d1372d982d.png)

![screenshot 2018-11-13 at 5 49 44 pm](https://user-images.githubusercontent.com/6906834/48425235-0f5ced80-e76d-11e8-8958-b3fd98028ac8.png)

I have tested on Safari and Chrome 

And here is the customer webiste: 

![screenshot 2018-11-13 at 5 54 30 pm](https://user-images.githubusercontent.com/6906834/48425366-5b0f9700-e76d-11e8-9a8c-0d1d9d25bdf8.png)

**Comment by roger-richards** [comment]
I created a stage copy with all plugins deactivated except woocommerce
and Intergeo
- Google Maps Plugin - Lite 2.2.3 and Intergeo Maps - Google Maps Plugin
Pro Add-on 1.4.3

https://winelab.net/stage1/


Regards,
Roger
