### ISSUE TITLE
migrate pro into free

### ISSUE THREAD

**Issue by selul** [Codeinwp/intergeo-maps#50]
@contactashish13 i would like to stop the working on the pro version and integrate it into the free version. We need to make sure that this will work ok for users who bought the pro one. 

after this i would like to make the next changes: 

* add a sidebar to the settings and maps page
* Add the next buttons : "Create New Map" + "View exising maps" to the settings page, in the top area, which will redirect user to : Media->Intergeo
* For the sidebar in settings and media -> intergeo use the same code, we will include there a subscription form, ajax based, similar with the one we have on pirate forms ( please check the plugin ) Make this part generic because we will include it in other plugins we own and it will need to work fine for all of them and to be pretty easy to configure.

**Comment by contactashish13** [comment]
@selul if someone has the pro version installed, they will need to uninstall it. or are you expecting it to work flawlessly when users download the new free version on an instance that has both free and pro activated?

**Comment by contactashish13** [comment]
@selul can you please confirm this is what you want in the settings sidebar and the maps sidebar?

settings page
- create new map pops up the add map popup
- view existing maps goes to the library

library/maps page
- subscription form

**Comment by contactashish13** [comment]
@selul in pirate forms are you talking about this? Its not an ajax based form.

![image](https://cloud.githubusercontent.com/assets/12953439/21184145/1ce794c2-c231-11e6-8297-cdb6c4559203.png)

**Comment by selul** [comment]
@contactashish13 regarding the settings page, those 2 btns will just redirect to the maps page, there is no fancy behaviour there, just a simple redirect.  Both btns will redirect to the same page . The buttons for the settings page will not be in the sidebar, will have the same placement as the add new is having on the LIbrary page. The sidebar will be the same for both of the pages

Regarding the subscription form, yes that's the one, and would be great if we can make it ajax based ;D 

When migrating the options you will need to make sure the pro version will still work with the new free and wont break users website.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/intergeo-maps/pull/51

this will work even if the pro is activated. this will show a nag notice to the user to delete the pro plugin.

**Comment by selul** [comment]
@contactashish13 can we remove the nag ? if is working fine with both active is fine for me.

**Comment by contactashish13** [comment]
@selul done

**Comment by selul** [comment]
@contactashish13 http://prntscr.com/djslsv what will do this enabled checkbox /

**Comment by contactashish13** [comment]
@selul if its unchecked, the imported markers will not be exported

**Comment by selul** [comment]
@contactashish13 let's remove the checkbox, when they click From Computer will automatically import the markers

**Comment by contactashish13** [comment]
@selul https://github.com/Codeinwp/intergeo-maps/pull/52
