### ISSUE TITLE
Custom map styles not working

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/intergeo-maps#61]
@selul Few users have reported that the custom map styles aren't working. 1.1.6 works. All versions after that are not working.

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/intergeo-maps/pull/75

**Comment by rodica-andronache** [comment]
@contactashish13 I see the custom style is not visible in the edit window https://prnt.sc/jri16m , when you try to edit an already created map https://prnt.sc/jri1fs. And also, the custom style is not updating the map when you add it, only after you close the window with Update the map.

**Comment by rodica-andronache** [comment]
@contactashish13 while testing this https://github.com/Codeinwp/intergeo-maps/pull/75, I encountered some stuff I don't understand if you could help:
At Overlays, Markers https://prnt.sc/jri6hz I added two blue markers, but they still appear red. 
And also the other tabs, Polylines, Rectangles, Circles, etc they seem to open, but when you click on them, nothing appears. 
Could you please check that?

**Comment by contactashish13** [comment]
@rodica-andronache you need to save the map for the red to turn blue. This does not behave like Visualizer - the map has to be saved.

Polylines, Rectangles, Circles, - after you click, you need to draw that shape on the map.

**Comment by rodica-andronache** [comment]
@contactashish13 I don't understand. Isn't that possible?
And even if we leave it like that. Isn't it a problem that after you click Create map ( with custom style ), you see it updated, but when you click to edit the map you get the old settings?

regarding the shape drawing, I finally understood how it's done, but it's quite difficult I think for the users. 
Would it be possible that in pro, we have a button in each of those sections Polylines, Rectangles, Circles etc, called Add Polyline, Add Rectangle and so on, that could activate that option, like if you've clicked on the top left icons? 
https://prnt.sc/js1e2k

**Comment by contactashish13** [comment]
@rodica-andronache have fixed the red/blue icon issue as part of #48 

I think having a button is a good suggestion. Will work on it. Maybe we can just make #48 a master issue?

**Comment by rodica-andronache** [comment]
@contactashish13 thanks.
But how about the custom style thing 'And even if we leave it like that. Isn't it a problem that after you click Create map ( with custom style ), you see it updated, but when you click to edit the map you get the old settings?'

**Comment by rodica-andronache** [comment]
@contactashish13 http://nimb.ws/aRZVBq Let me know if you can replicate it :)

**Comment by contactashish13** [comment]
@rodica-andronache I cannot reproduce this behavior even when I follow your steps exactly.

**Comment by rodica-andronache** [comment]
@contactashish13 just to be sure, did you used https://github.com/Codeinwp/intergeo-maps/pull/77 and for the json, did you just copy and paste it? from you screenshot, the json seems a bit different formatted then what I had. Maybe you can share a video too 👍

**Comment by contactashish13** [comment]
@rodica-andronache I used https://github.com/Codeinwp/intergeo-maps/pull/77 and as you can see it works correctly changing the map to a dark theme. The whitespace is removed from JSON once it is saved so that's not an issue.

https://drive.google.com/file/d/1Qx0y21opwuYfjynD-xCI4Yj2YzrU11m4/view

**Comment by mileamadalin** [comment]
Unfortunately, I cannot reply to that ticket anymore.
