### ISSUE TITLE
Blue markers don't show up when chosen from add markers area

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#63]
https://github.com/Codeinwp/intergeo-maps-pro/issues/32

**Comment by HardeepAsrani** [comment]
@selul 

+1

**Comment by contactashish13** [comment]
@rodica-andronache https://github.com/Codeinwp/intergeo-maps-pro/issues/32 seems to be resolved. If that's not the case, can you please clarify what investigation this requires?

**Comment by rodica-andronache** [comment]
@contactashish13 I think I answered here https://github.com/Codeinwp/intergeo-maps/issues/61. Didn't test with the pro version, but in the lite version, it wasn't working for me. If you could check

**Comment by contactashish13** [comment]
@rodica-andronache the issue mentioned in https://github.com/Codeinwp/intergeo-maps-pro/issues/32 is different from the issue you mentioned in https://github.com/Codeinwp/intergeo-maps/issues/61. Please clarify.
