### ISSUE TITLE
Multiple Maps on single page are not showing

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/intergeo-maps#87]
If we add multiple maps on single post, only the first one shows. 

- The issue comes with both Gutenberg and Classic Editor.
- If we rollback the plugin to older version, it works. 

Ticket: https://wordpress.org/support/topic/intergeo-maps-dont-works/#post-11366001

@contactashish13

**Comment by contactashish13** [comment]
@Vishakha-Patel I cannot reproduce this behavior. Please check https://overseas-beaver.jurassic.ninja/2019/04/23/intergeo/ - this has PR #86 applied. Even without the PR, I can see multiple maps **if they have already been created before**.  If you need the credentials to test, ping me on slack.

**Comment by Vishakha-Patel** [comment]
@contactashish13,

I am checking this and trying to find the difference between your installation and mine. Will update here.

**Comment by Vishakha-Patel** [comment]
@contactashish13 

Worked for me on Jurassic Ninja after applying PR #86. 

Without PR - http://prntscr.com/nk8ng8 version 2.3.0
With PR - http://prntscr.com/nk8nns
