### ISSUE TITLE
Recommend Otter's Map Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/intergeo-maps#89]
Should we recommend people to install and use Otter's map block? @selul

**Comment by selul** [comment]
@HardeepAsrani we already do this in the sidebar of Intergeo I think. 

Do you have something else in mind?

**Comment by HardeepAsrani** [comment]
Right now it recommends Otter without any indication that it even has a Google Map block. Maybe something more clear with a video?

<img width="1647" alt="Screen Shot 2019-05-22 at 2 24 06 AM" src="https://user-images.githubusercontent.com/2649903/58130059-c9f80c00-7c38-11e9-868f-076cf32b8f37.png">

**Comment by selul** [comment]
@HardeepAsrani makes sense, 

you can add a more targeted notice for users with WP>5 telling them about Otter maps block.

For users with WP<5 we can show the current sidebar Otter block. 

What do you think?

**Comment by HardeepAsrani** [comment]
@selul Sounds good. For users with WP 5+, we can show a video with a message in "Library" page if they don't have any Maps present, like this:

![58130059-c9f80c00-7c38-11e9-868f-076cf32b8f37](https://user-images.githubusercontent.com/2649903/58209705-2b85ac80-7d05-11e9-99fe-902553b749e6.png)

And if a user has few maps, maybe we can show it like this:

<img width="1650" alt="Screen Shot 2019-05-23 at 2 54 19 AM" src="https://user-images.githubusercontent.com/2649903/58210222-7653f400-7d06-11e9-9db6-d58aca7ec7c7.png">

And maybe here in the sidebar:

<img width="1302" alt="Screen Shot 2019-05-23 at 2 57 34 AM" src="https://user-images.githubusercontent.com/2649903/58210249-8c61b480-7d06-11e9-8973-7160f5d03bb0.png">

What do you think? We should try to migrate the users from Intergeo to Otter. Google Maps block is pretty neat so we can promote this better.

**Comment by selul** [comment]
@HardeepAsrani seems a bit too intrusive all of them. 

We can show just notice similar to how WordPress adds in the dashboard http://prntscr.com/ns9qzw or how we recommend starter sites when you install neve  

What do you think?

**Comment by HardeepAsrani** [comment]
Yea, we can do something like this.

**Comment by HardeepAsrani** [comment]
Can we decide what we should show? Something that will convert people. Not sure what will be the best way. Maybe @ineagu knows?

**Comment by ineagu** [comment]
Honestly for me we can come up with a big wpforms like notice, retire intergeo and ask people to use otter. Doesn't make sense to keep maintaining that.

**Comment by HardeepAsrani** [comment]
@ineagu Issue with that is that current users can't just change Intergeo to Otter as their existing maps won't work. :)

**Comment by ineagu** [comment]
Bad luck :))

Jokes aside, we can let them know that, that we recommend to switch and that they would need to redo the charts, so better run those in same time for a while
